name: aquila
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # external packages

  flutter_riverpod: ^2.6.1
  dio: ^5.7.0
  fpdart: ^1.1.1

  elegant_notification: ^2.4.1
  shared_preferences: ^2.3.5

  #UI
  typewritertext: ^3.0.9
  animate_do: ^3.3.4
  flutter_spinkit: ^5.2.1
  shimmer: ^3.0.0
  implicitly_animated_reorderable_list_2: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
